name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:

  # build the environment
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11




  # dev env
  dev:
    runs-on: ubuntu-latest
    environment: DEV
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        run: |
          pip install mkdocs
          mkdocs build
          echo "files in main branch"
          ls -la
          git checkout -b gh-pages
          echo "files in gh-pages branch"
          ls -la
          cp site/* .
          echo "files within site"
          ls -la
          git push origin gh-pages
        env:
          DEV_SECRET: ${{ secrets.DEV_SECRET }}
