name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:

  # build the environment
  build:
    runs-on: linux

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11






  # test env
  test:
    runs-on: linux
    environment: TEST
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Identify Git Credentials
        run: |
          git config user.email "bsk.pradip@gmail.com"
          git config user.name "pradipbasak"

      - name: Build site directory
        run: |
          pip install mkdocs
          mkdocs build
          git checkout -b test
          git add site
          git commit -m "added site directory to the test branch"
          git push --force origin test
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}


  # prod env
  prod:
    runs-on: linux
    environment: PROD
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build site directory
        run: |
          pip install mkdocs
          mkdocs gh-deploy --force -b gh-pages
        env:
          PROD_SECRET: ${{ secrets.PROD_SECRET }}

