name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install mkdocs

      - name: Build MkDocs
        run: mkdocs build


  dev:
    runs-on: ubuntu-latest
    environment: DEV
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        run: |
          git checkout -b gh-pages
          git rm -rf .
          mkdir -p site
          cp -r site/* site/
          git add .
          git commit -m "Deploy MkDocs to GitHub Pages"
          git push origin gh-pages
        env:
          DEV_SECRET: ${{ secrets.DEV_SECRET }}

  test:
    runs-on: ubuntu-latest
    environment: TEST
    needs: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        run: |
          git checkout -b gh-pages
          git rm -rf .
          mkdir -p site
          cp -r dev/site/* site/
          git add .
          git commit -m "Deploy MkDocs to GitHub Pages"
          git push origin gh-pages
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}

  prod:
    runs-on: ubuntu-latest
    environment: PROD
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        run: |
          git checkout -b gh-pages
          git rm -rf .
          mkdir -p site
          cp -r test/site/* site/
          git add .
          git commit -m "Deploy MkDocs to GitHub Pages"
          git push origin gh-pages
        env:
          PROD_SECRET: ${{ secrets.PROD_SECRET }}
