name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:

  # build the environment
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11




  # dev env
  dev:
    runs-on: ubuntu-latest
    environment: DEV
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        run: |
          pip install mkdocs
          mkdocs build
          git checkout -b gh-pages
          git rm -rf .
          git checkout main -- site
          git add site
          cp site/* .
          git rm -rf site
          git push origin gh-pages
        env:
          DEV_SECRET: ${{ secrets.DEV_SECRET }}
