name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:

  # build the environment
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11




  # test env
  test:
    runs-on: ubuntu-latest
    environment: TEST
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build site directory
        run: |
          pip install mkdocs
          mkdocs build
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}

      - name: Deploy Test site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site